#include <stdlib.h>
#include <stdio.h>
#include <yaml.h>

yaml_token_t    yaml_token;
yaml_event_t    yaml_event;
yaml_node_t     yaml_node;
yaml_document_t yaml_document;
yaml_parser_t   yaml_parser;
yaml_emitter_t yaml_emitter;

int main() {
printf("%ld\n", sizeof(yaml_version_directive_t));
printf("%ld\n", sizeof(yaml_tag_directive_t));
printf("%ld\n", sizeof(yaml_mark_t));
printf("%ld\n", sizeof(yaml_token.data.stream_start));
printf("%ld\n", sizeof(yaml_token.data.alias));
printf("%ld\n", sizeof(yaml_token.data.anchor));
printf("%ld\n", sizeof(yaml_token.data.tag));
printf("%ld\n", sizeof(yaml_token.data.scalar));
printf("%ld\n", sizeof(yaml_token.data.version_directive));
printf("%ld\n", sizeof(yaml_token_t));
printf("%ld\n", sizeof(yaml_event.data.stream_start));
printf("%ld\n", sizeof(yaml_event.data.document_start.tag_directives));
printf("%ld\n", sizeof(yaml_event.data.document_start));
printf("%ld\n", sizeof(yaml_event.data.document_end));
printf("%ld\n", sizeof(yaml_event.data.alias));
printf("%ld\n", sizeof(yaml_event.data.scalar));
printf("%ld\n", sizeof(yaml_event.data.sequence_start));
printf("%ld\n", sizeof(yaml_event.data.mapping_start));
printf("%ld\n", sizeof(yaml_event_t));
printf("%ld\n", sizeof(yaml_node_pair_t));
printf("%ld\n", sizeof(yaml_node.data.scalar));
printf("%ld\n", sizeof(yaml_node.data.sequence.items));
printf("%ld\n", sizeof(yaml_node.data.sequence));
printf("%ld\n", sizeof(yaml_node.data.mapping.pairs));
printf("%ld\n", sizeof(yaml_node.data.mapping));
printf("%ld\n", sizeof(yaml_node_t));
printf("%ld\n", sizeof(yaml_document.nodes));
printf("%ld\n", sizeof(yaml_document.tag_directives));
printf("%ld\n", sizeof(yaml_document_t));
printf("%ld\n", sizeof(yaml_simple_key_t));
printf("%ld\n", sizeof(yaml_alias_data_t));
printf("%ld\n", sizeof(yaml_parser.input.string));
printf("%ld\n", sizeof(yaml_parser.buffer));
printf("%ld\n", sizeof(yaml_parser.raw_buffer));
printf("%ld\n", sizeof(yaml_parser.tokens));
printf("%ld\n", sizeof(yaml_parser.indents));
printf("%ld\n", sizeof(yaml_parser.simple_keys));
printf("%ld\n", sizeof(yaml_parser.states));
printf("%ld\n", sizeof(yaml_parser.marks));
printf("%ld\n", sizeof(yaml_parser.tag_directives));
printf("%ld\n", sizeof(yaml_parser.aliases));
printf("%ld\n", sizeof(yaml_parser_t));
printf("%ld\n", sizeof(yaml_emitter.output.string));
printf("%ld\n", sizeof(yaml_emitter.buffer));
printf("%ld\n", sizeof(yaml_emitter.raw_buffer));
printf("%ld\n", sizeof(yaml_emitter.states));
printf("%ld\n", sizeof(yaml_emitter.events));
printf("%ld\n", sizeof(yaml_emitter.indents));
printf("%ld\n", sizeof(yaml_emitter.tag_directives));
printf("%ld\n", sizeof(yaml_emitter.anchor_data));
printf("%ld\n", sizeof(yaml_emitter.tag_data));
printf("%ld\n", sizeof(yaml_emitter.scalar_data));
printf("%ld\n", sizeof(*(yaml_emitter.anchors)));
printf("%ld\n", sizeof(yaml_emitter_t));
}
