#!/bin/sh

if [ \( `uname -s ` = FreeBSD \) -a \( `uname -p` = i386 \) ]
then
  echo freebsd-x86-32
elif [ \( `uname -s` = Darwin \) -a \( `uname -p` = powerpc \) ]
then
  echo macosx-ppc
elif [ `uname -s` = Darwin ]
then
  echo macosx-x86-`./misc/wordsize`
elif [ \( `uname -s` = Linux \) -a \( `uname -m` = i686 \) ]
then
  echo linux-x86-32
elif [ \( `uname -s` = Linux \) -a \( `uname -m` = x86_64 \) ]
then
  echo linux-x86-64
elif [ \( `uname -o` = Cygwin \) -a \( `uname -m` = i686 \) ]
then
  echo winnt-x86-`./misc/wordsize`
else
  echo help
fi
