/* :folding=explicit:collapseFolds=1: */

/*
 * $Id$
 *
 * Copyright (C) 2003, 2004 Slava Pestov.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * DEVELOPERS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package factor;

import java.lang.reflect.*;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

/**
 * A few methods for converting between Java types, and making reflection calls.
 * Note that the compiler incorporates calls to some of these methods in
 * generated bytecode.
 */
public class FactorJava
{
	public static final Class[] EMPTY_ARRAY = new Class[0];

	//{{{ classNameToClassList() method
	public static Class[] classNameToClassList(FactorList classes)
		throws Exception
	{
		if(classes == null)
			return EMPTY_ARRAY;

		Class[] _classes = new Class[classes.length()];
		int i = 0;
		while(classes != null)
		{
			_classes[i++] = (Class)classes.car(Class.class);
			classes = classes.next();
		}

		return _classes;
	} //}}}

	//{{{ toNumber() method
	public static Number toNumber(Object arg)
		throws FactorDomainException
	{
		if(arg instanceof Number)
			return (Number)arg;
		else if(arg instanceof String)
		{
			String str = (String)arg;
			if(str.indexOf('.') != -1)
				return new Float(str);
			else
				return new Integer(str);
		}
		else
			throw new FactorDomainException(arg,Number.class);
	} //}}}

	//{{{ toString() method
	public static String toString(Object arg)
	{
		if(arg == null)
			return null;
		else if(arg instanceof String)
			return (String)arg;
		else
			return String.valueOf(arg);
	} //}}}

	//{{{ toBoolean() method
	public static boolean toBoolean(Object arg)
	{
		if(Boolean.FALSE.equals(arg) || arg == null)
			return false;
		else
			return true;
	} //}}}

	//{{{ toChar() method
	public static char toChar(Object arg)
		throws FactorDomainException
	{
		if(arg instanceof Character)
			return ((Character)arg).charValue();
		else if(arg == null)
			return '\0';
		else if(arg instanceof String)
		{
			String s = (String)arg;
			if(s.length() != 1)
				throw new FactorDomainException(arg,char.class);
			return s.charAt(0);
		}
		else if(arg instanceof Number)
		{
			return (char)((Number)arg).intValue();
		}
		else
			throw new FactorDomainException(arg,char.class);
	} //}}}

	//{{{ toInt() method
	public static int toInt(Object arg)
		throws FactorDomainException
	{
		if(arg instanceof Number)
			return ((Number)arg).intValue();
		else if(arg instanceof String)
			return Integer.parseInt((String)arg);
		else
			throw new FactorDomainException(arg,int.class);
	} //}}}

	//{{{ toLong() method
	public static long toLong(Object arg)
		throws FactorDomainException
	{
		if(arg instanceof Number)
			return ((Number)arg).longValue();
		else if(arg instanceof String)
			return Long.parseLong((String)arg);
		else
			throw new FactorDomainException(arg,long.class);
	} //}}}

	//{{{ toFloat() method
	public static float toFloat(Object arg)
		throws FactorDomainException
	{
		if(arg instanceof Number)
			return ((Number)arg).floatValue();
		else if(arg instanceof String)
			return Float.parseFloat((String)arg);
		else
			throw new FactorDomainException(arg,float.class);
	} //}}}

	//{{{ toDouble() method
	public static double toDouble(Object arg)
		throws FactorDomainException
	{
		if(arg instanceof Number)
			return ((Number)arg).doubleValue();
		else if(arg instanceof String)
			return Double.parseDouble((String)arg);
		else
			throw new FactorDomainException(arg,double.class);
	} //}}}

	//{{{ toClass() method
	public static Class toClass(Object arg)
		throws Exception
	{
		if(arg instanceof Class)
			return (Class)arg;
		else
		{
			return getClass((String)
				convertToJavaType(arg,String.class));
		}
	} //}}}

	//{{{ toArray() method
	public static Object[] toArray(Object arg)
		throws FactorDomainException
	{
		return toArray(arg,Object.class);
	} //}}}

	//{{{ toArray() method
	public static Object[] toArray(Object arg, Class clas)
		throws FactorDomainException
	{
		if(arg instanceof FactorList)
		{
			FactorList list = (FactorList)arg;
			Object[] array = (Object[])
				Array.newInstance(
				clas.getComponentType(),
				list.length());
			list.toArray(array);
			return array;
		}
		else if(arg.getClass().isArray())
			return (Object[])arg;
		else
			throw new FactorDomainException(arg,Object[].class);
	} //}}}

	//{{{ convertToJavaType() method
	public static Object convertToJavaType(Object arg, Class clas)
		throws Exception
	{
		if(clas == Object.class)
			return arg;
		else if(clas == Number.class)
		{
			return toNumber(arg);
		}
		else if(clas == String.class)
		{
			return toString(arg);
		}
		else if(clas == boolean.class)
		{
			return toBoolean(arg)
				? Boolean.TRUE
				: Boolean.FALSE;
		}
		else if(clas == char.class)
		{
			return new Character(toChar(arg));
		}
		else if(clas == int.class)
		{
			return new Integer(toInt(arg));
		}
		else if(clas == long.class)
		{
			return new Long(toLong(arg));
		}
		else if(clas == float.class)
		{
			return new Float(toFloat(arg));
		}
		else if(clas == double.class)
		{
			return new Double(toDouble(arg));
		}
		else if(clas == Class.class)
		{
			return toClass(arg);
		}
		else if(clas.isArray())
		{
			return toArray(arg,clas);
		}

		if(arg != null && !clas.isInstance(arg))
			throw new FactorDomainException(arg,clas);
		else
			return arg;
	} //}}}

	//{{{ fromBoolean() method
	public static Object fromBoolean(boolean b)
	{
		return (b ? Boolean.TRUE : null);
	} //}}}

	//{{{ convertFromJavaType() method
	public static Object convertFromJavaType(Object arg)
	{
		if(Boolean.FALSE.equals(arg))
			return null;
		else
			return arg;
	} //}}}

	//{{{ factorTypeToString() method
	public static String factorTypeToString(Object obj)
	{
		// this is for string representations of lists and stacks
		if(obj == null || obj.equals(Boolean.FALSE))
			return "f";
		else if(obj.equals(Boolean.TRUE))
			return "t";
		else if(obj instanceof String)
			return '"' + obj.toString() + '"'; //XXX: escape
		else if(obj instanceof Number
			|| obj instanceof FactorExternalizable)
			return obj.toString();
		else if(obj instanceof Character)
			return "#\\" + ((Character)obj).charValue();
		else
			return "(" + obj + ")";
	} //}}}

	//{{{ javaClassToVMClass() method
	public static String javaClassToVMClass(Class clazz)
	{
		String name = clazz.getName();

		if(clazz.isArray())
			return clazz.getName().replace('.','/');
		else if(name.equals("boolean"))
			return "Z";
		else if(name.equals("byte"))
			return "B";
		else if(name.equals("char"))
			return "C";
		else if(name.equals("double"))
			return "D";
		else if(name.equals("float"))
			return "F";
		else if(name.equals("int"))
			return "I";
		else if(name.equals("long"))
			return "J";
		else if(name.equals("short"))
			return "S";
		else if(name.equals("void"))
			return "V";
		else
			return "L" + clazz.getName().replace('.','/') + ";";
	} //}}}

	//{{{ javaBoxingType() method
	public static Class javaBoxingType(Class clazz)
	{
		if(clazz == Byte.TYPE)
			return Byte.class;
		else if(clazz == Character.TYPE)
			return Character.class;
		else if(clazz == Double.TYPE)
			return Double.class;
		else if(clazz == Float.TYPE)
			return Float.class;
		else if(clazz == Integer.TYPE)
			return Integer.class;
		else if(clazz == Long.TYPE)
			return Long.class;
		else if(clazz == Short.TYPE)
			return Short.class;
		else
			return null;
	} //}}}

	//{{{ javaSignatureToVMSignature() method
	public static String javaSignatureToVMSignature(Class[] args,
		Class returnType)
	{
		StringBuffer buf = new StringBuffer("(");
		for(int i = 0; i < args.length; i++)
		{
			buf.append(javaClassToVMClass(args[i]));
		}
		buf.append(")");
		buf.append(javaClassToVMClass(returnType));
		return buf.toString();
	} //}}}

	//{{{ getClass() method
	public static Class getClass(String name) throws ClassNotFoundException
	{
		if(name.equals("boolean"))
			return Boolean.TYPE;
		else if(name.equals("byte"))
			return Byte.TYPE;
		else if(name.equals("char"))
			return Character.TYPE;
		else if(name.equals("double"))
			return Double.TYPE;
		else if(name.equals("float"))
			return Float.TYPE;
		else if(name.equals("int"))
			return Integer.TYPE;
		else if(name.equals("long"))
			return Long.TYPE;
		else if(name.equals("short"))
			return Short.TYPE;
		else
			return Class.forName(name);
	} //}}}

	//{{{ jconstructor() method
	public static Constructor jconstructor(String inClass, FactorList args)
		throws Exception
	{
		return Class.forName(inClass).getConstructor(
			classNameToClassList(args));
	} //}}}

	//{{{ jfield() method
	public static Field jfield(String field, String inClass)
		throws Exception
	{
		return Class.forName(inClass).getField(field);
	} //}}}

	//{{{ jinvoke() method
	public static void jinvoke(FactorDataStack stack, Method method,
		Object instance) throws Exception
	{
		if(instance != null)
		{
			instance = convertToJavaType(instance,
				method.getDeclaringClass());
		}

		Class[] paramTypes = method.getParameterTypes();
		Object[] args = new Object[paramTypes.length];

		try
		{
			for(int i = args.length - 1; i >= 0; i--)
			{
				args[i] = convertToJavaType(stack.pop(),
					paramTypes[i]);
			}

			if(Modifier.isStatic(method.getModifiers()))
			{
				if(instance != null)
					throw new FactorRuntimeException(
						"Use jinvokeStatic with static methods");
			}
			else
			{
				if(instance == null)
					throw new FactorRuntimeException(
						"Cannot jinvoke on f");
			}

			if(method.getReturnType() == Void.TYPE)
				method.invoke(instance,args);
			else
			{
				stack.push(convertFromJavaType(
					method.invoke(instance,args)));
			}
		}
		catch(FactorStackException e)
		{
			throw new FactorStackException(paramTypes.length);
		}
	} //}}}

	//{{{ jinvokeStatic() method
	public static void jinvokeStatic(FactorDataStack stack, Method method)
		throws Exception
	{
		jinvoke(stack,method,null);
	} //}}}

	//{{{ jmethod() method
	public static Method jmethod(String method, String inClass,
		FactorList args) throws Exception
	{
		return Class.forName(inClass).getMethod(method,
			classNameToClassList(args));
	} //}}}

	//{{{ jnew() method
	public static void jnew(FactorDataStack stack, Constructor method)
		throws Exception
	{
		Class[] paramTypes = method.getParameterTypes();
		Object[] args = new Object[paramTypes.length];
		for(int i = args.length - 1; i >= 0; i--)
		{
			args[i] = convertToJavaType(stack.pop(),
				paramTypes[i]);
		}
	        
		stack.push(method.newInstance(args));
	} //}}}

	//{{{ jvarGet() method
	public static Object jvarGet(Field field, Object obj) throws Exception
	{
		return convertFromJavaType(field.get(obj));
	} //}}}

	//{{{ jvarGetStatic() method
	public static Object jvarGetStatic(Field field) throws Exception
	{
		return convertFromJavaType(field.get(null));
	} //}}}

	//{{{ jvarSet() method
	public static void jvarSet(Field field, Object obj, Object value)
		throws Exception
	{
		field.set(obj,convertToJavaType(value,field.getType()));
	} //}}}

	//{{{ jvarSetStatic() method
	public static void jvarSetStatic(Field field, Object value)
		throws Exception
	{
		field.set(null,convertToJavaType(value,field.getType()));
	} //}}}

	//{{{ unwrapException() method
	public static Throwable unwrapException(Throwable e)
	{
		if(e instanceof InvocationTargetException)
		{
			return unwrapException(
				((InvocationTargetException)e)
				.getTargetException());
		}
		else if(e.getCause() != null)
			return unwrapException(e.getCause());
		else
			return e;
	} //}}}
}
