#!/bin/sh

uname_s=`uname -s`
case $uname_s in
	CYGWIN_NT-5.2-WOW64) OS=winnt;;
	*CYGWIN_NT*) OS=winnt;;
	*CYGWIN*) OS=winnt;;
	*darwin*) OS=macosx;;
	*Darwin*) OS=macosx;;
	*linux*) OS=linux;;
	*Linux*) OS=linux;;
	*NetBSD*) OS=netbsd;;
	*FreeBSD*) OS=freebsd;;
	*OpenBSD*) OS=openbsd;;
	*DragonFly*) OS=dragonflybsd;;
esac

uname_m=`uname -m`
case $uname_m in
   i386) ARCH=x86;;
   i686) ARCH=x86;;
   amd64) ARCH=x86;;
   *86) ARCH=x86;;
   *86_64) ARCH=x86;;
   "Power Macintosh") ARCH=ppc;;
esac

WORD=`./build-support/wordsize`

MAKE_TARGET=$OS-$ARCH-$WORD
if [[ $OS == macosx && $ARCH == ppc ]] ; then
	MAKE_TARGET=$OS-$ARCH
fi
if [[ $OS == linux && $ARCH == ppc ]] ; then
	MAKE_TARGET=$OS-$ARCH
fi

echo $MAKE_TARGET
