USING: io kernel sequences vocabs.loader ;
{
    "cpu.architecture"
    "compiler.cfg.instructions"
    "compiler.cfg.def-use"
    "compiler.cfg.hats"
    "compiler.cfg.renaming.functor"
    "compiler.cfg.renaming"
    "compiler.cfg.linear-scan.assignment"
    "compiler.cfg.representations.rewrite"
    "compiler.cfg.ssa.construction"
    "compiler.cfg.representations.preferred"
    "compiler.cfg.value-numbering.expressions"
    "compiler.codegen"
    "cpu.arm.64.assembler"
    "cpu.arm.64"
    "compiler.cfg.value-numbering.graph"
    "compiler.cfg.value-numbering.folding"
    "compiler.cfg.value-numbering.math"
    "compiler.cfg.value-numbering"
    "compiler.cfg.multiply-negate"
    "compiler.cfg.optimizer"
} [ dup print flush reload ] each
