PROVIDE: core/tools
{ +files+ {
    "definitions.factor"
    "editor.factor"
    "completion.factor"
    "memory.factor"
    "time.factor"
    "test.factor"
    "modules.factor"
    "image.factor"
    "interpreter.factor"
    "word-tools.factor"
    "errors.factor"
    "debugger.factor"
    "profiler.factor"
    "completion.facts"
    "debugger.facts"
    "definitions.facts"
    "editor.facts"
    "image.facts"
    "image.facts"
    "interpreter.facts"
    "memory.facts"
    "modules.facts"
    "test.facts"
    "time.facts"
    "word-tools.facts"
} }
{ +tests+ {
    "test/annotate.factor"
    "test/interpreter.factor"
    "test/memory.factor"
    "test/tools.factor"
    "test/word-tools.factor"
} } ;
