#!/usr/bin/env python3
"""Summarize execution-rate variation and static metrics from an accepted matrix."""
import argparse
import gzip
import json
import math
import statistics
from pathlib import Path

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('directory', type=Path)
a = p.parse_args()
collection = json.loads((a.directory / 'collection.json').read_text())
assert collection['accepted'] and collection['measured_batches'] == 1404
summary = json.loads((a.directory / 'summary.json').read_text())
runs = {}
candidate_samples = {}
for path in sorted(a.directory.glob('*-timing-*.jsonl.gz')):
    name = path.name.removesuffix('.jsonl.gz')
    rows = [json.loads(line) for line in gzip.open(path, 'rt')]
    status = json.loads(path.with_name(name + '.status.json').read_text())
    compile_row = next(row for row in rows if row['kind'] == 'compile')
    runtime = [row for row in rows if row['kind'] == 'runtime' and row['trial'] >= 0]
    if name.startswith('candidate-'):
        allocator, ordinal = name.removeprefix('candidate-timing-').rsplit('-', 1)
        candidate_samples[(allocator, ordinal)] = runtime
    cpu = sum(row['cpu_seconds'] for row in runtime)
    wall = sum(row['ns'] for row in runtime) / 1e9
    retired = sum(row['instructions'] for row in runtime)
    runs[name] = dict(
        host_load_before=status['host_load_before'], host_load_after=status['host_load_after'],
        process_wall_seconds=status['seconds'],
        compile_cpu_seconds=compile_row['cpu_seconds'],
        compile_wall_seconds=compile_row['ns'] / 1e9,
        compile_retired=compile_row['instructions'],
        compile_giga_instructions_per_cpu_second=compile_row['instructions'] / compile_row['cpu_seconds'] / 1e9,
        runtime_cpu_seconds=cpu, runtime_wall_seconds=wall, runtime_retired=retired,
        runtime_giga_instructions_per_cpu_second=retired / cpu / 1e9,
        runtime_wall_over_cpu=wall / cpu)
assert len(runs) == 18
static = {}
for allocator, report in summary['allocators'].items():
    static[allocator] = {}
    for label, kernels in report['code'].items():
        assert len(kernels) == 12
        static[allocator][label] = {metric: sum(kernel[metric] for kernel in kernels.values())
                                     for metric in next(iter(kernels.values()))}
loads = [run[key][0] for run in runs.values() for key in ('host_load_before', 'host_load_after')]
rank_by_round = {}
for ordinal in ('1', '2'):
    rank_by_round[ordinal] = {}
    reference = candidate_samples[('linear-scan', ordinal)]
    words = {row['word'] for row in reference}
    for allocator in summary['allocators']:
        samples = candidate_samples[(allocator, ordinal)]
        ratios = {}
        for metric in ('cpu_seconds', 'ns', 'instructions'):
            pairs = [[statistics.median(row[metric] / row['iterations'] for row in rows if row['word'] == word)
                      for rows in (reference, samples)] for word in sorted(words)]
            ratios[metric] = math.exp(statistics.mean(math.log(candidate / baseline) for baseline, candidate in pairs))
        rank_by_round[ordinal][allocator] = ratios
result = dict(host_load_1m_min=min(loads), host_load_1m_max=max(loads),
              host_load_1m_median=statistics.median(loads), runs=runs,
              final_allocator_over_linear_scan_by_round=rank_by_round,
              static_12_kernel_totals=static,
              note='Runtime totals describe execution-rate context, not equally weighted workload rankings. Static counts are sums across twelve separately compiled kernels. Spills, reloads and copies count final machine-IR opcodes, not dynamic events or emitted machine instructions. Equal-register copies can emit no instruction; code-bytes measures actual generated bytes.')
(a.directory / 'diagnostics.json').write_text(json.dumps(result, indent=2) + '\n')
lines = ['# Execution-rate and static-code diagnostics', '', result['note'], '',
         '| Run | Load before | Compile CPU s | Compile Ginst/CPU s | Runtime wall/CPU |',
         '|---|---:|---:|---:|---:|']
for name, run in runs.items():
    lines.append(f"| {name} | {run['host_load_before'][0]:.2f} | {run['compile_cpu_seconds']:.2f} | {run['compile_giga_instructions_per_cpu_second']:.2f} | {run['runtime_wall_over_cpu']:.3f} |")
lines += ['', '| Allocator / revision | Code bytes | Spills | Reloads | Copies | Spill bytes |',
          '|---|---:|---:|---:|---:|---:|']
for allocator, revisions in static.items():
    for label, values in revisions.items():
        lines.append('| ' + allocator + ' / ' + label + ' | ' + ' | '.join(str(values[key]) for key in ('code-bytes', 'spills', 'reloads', 'copies', 'spill-bytes')) + ' |')
(a.directory / 'diagnostics.md').write_text('\n'.join(lines) + '\n')
