! Generated by header-audit.py. Compare output to native C layout-oracle.c.
USING: alien.c-types classes.struct continuations db.sqlite.ffi io kernel prettyprint vocabs.loader ;
IN: scratchpad
<< "db.sqlite.ffi" reload >>
"LAYOUT sqlite3_file size " write [ sqlite3_file heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_file align " write [ sqlite3_file c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_file pMethods " write [ "pMethods" sqlite3_file offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods size " write [ sqlite3_io_methods heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods align " write [ sqlite3_io_methods c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods iVersion " write [ "iVersion" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xClose " write [ "xClose" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xRead " write [ "xRead" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xWrite " write [ "xWrite" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xTruncate " write [ "xTruncate" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xSync " write [ "xSync" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xFileSize " write [ "xFileSize" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xLock " write [ "xLock" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xUnlock " write [ "xUnlock" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xCheckReservedLock " write [ "xCheckReservedLock" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xFileControl " write [ "xFileControl" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xSectorSize " write [ "xSectorSize" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xDeviceCharacteristics " write [ "xDeviceCharacteristics" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xShmMap " write [ "xShmMap" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xShmLock " write [ "xShmLock" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xShmBarrier " write [ "xShmBarrier" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xShmUnmap " write [ "xShmUnmap" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xFetch " write [ "xFetch" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_io_methods xUnfetch " write [ "xUnfetch" sqlite3_io_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs size " write [ sqlite3_vfs heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs align " write [ sqlite3_vfs c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs iVersion " write [ "iVersion" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs szOsFile " write [ "szOsFile" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs mxPathname " write [ "mxPathname" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs pNext " write [ "pNext" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs zName " write [ "zName" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs pAppData " write [ "pAppData" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xOpen " write [ "xOpen" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xDelete " write [ "xDelete" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xAccess " write [ "xAccess" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xFullPathname " write [ "xFullPathname" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xDlOpen " write [ "xDlOpen" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xDlError " write [ "xDlError" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xDlSym " write [ "xDlSym" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xDlClose " write [ "xDlClose" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xRandomness " write [ "xRandomness" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xSleep " write [ "xSleep" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xCurrentTime " write [ "xCurrentTime" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xGetLastError " write [ "xGetLastError" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xCurrentTimeInt64 " write [ "xCurrentTimeInt64" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xSetSystemCall " write [ "xSetSystemCall" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xGetSystemCall " write [ "xGetSystemCall" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vfs xNextSystemCall " write [ "xNextSystemCall" sqlite3_vfs offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods size " write [ sqlite3_mem_methods heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods align " write [ sqlite3_mem_methods c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods xMalloc " write [ "xMalloc" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods xFree " write [ "xFree" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods xRealloc " write [ "xRealloc" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods xSize " write [ "xSize" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods xRoundup " write [ "xRoundup" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods xInit " write [ "xInit" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods xShutdown " write [ "xShutdown" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mem_methods pAppData " write [ "pAppData" sqlite3_mem_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module size " write [ sqlite3_module heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module align " write [ sqlite3_module c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module iVersion " write [ "iVersion" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xCreate " write [ "xCreate" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xConnect " write [ "xConnect" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xBestIndex " write [ "xBestIndex" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xDisconnect " write [ "xDisconnect" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xDestroy " write [ "xDestroy" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xOpen " write [ "xOpen" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xClose " write [ "xClose" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xFilter " write [ "xFilter" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xNext " write [ "xNext" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xEof " write [ "xEof" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xColumn " write [ "xColumn" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xRowid " write [ "xRowid" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xUpdate " write [ "xUpdate" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xBegin " write [ "xBegin" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xSync " write [ "xSync" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xCommit " write [ "xCommit" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xRollback " write [ "xRollback" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xFindFunction " write [ "xFindFunction" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xRename " write [ "xRename" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xSavepoint " write [ "xSavepoint" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xRelease " write [ "xRelease" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xRollbackTo " write [ "xRollbackTo" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xShadowName " write [ "xShadowName" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_module xIntegrity " write [ "xIntegrity" sqlite3_module offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info size " write [ sqlite3_index_info heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info align " write [ sqlite3_index_info c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info nConstraint " write [ "nConstraint" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info aConstraint " write [ "aConstraint" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info nOrderBy " write [ "nOrderBy" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info aOrderBy " write [ "aOrderBy" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info aConstraintUsage " write [ "aConstraintUsage" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info idxNum " write [ "idxNum" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info idxStr " write [ "idxStr" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info needToFreeIdxStr " write [ "needToFreeIdxStr" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info orderByConsumed " write [ "orderByConsumed" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info estimatedCost " write [ "estimatedCost" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info estimatedRows " write [ "estimatedRows" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info idxFlags " write [ "idxFlags" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_info colUsed " write [ "colUsed" sqlite3_index_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint size " write [ sqlite3_index_constraint heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint align " write [ sqlite3_index_constraint c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint iColumn " write [ "iColumn" sqlite3_index_constraint offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint op " write [ "op" sqlite3_index_constraint offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint usable " write [ "usable" sqlite3_index_constraint offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint iTermOffset " write [ "iTermOffset" sqlite3_index_constraint offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_orderby size " write [ sqlite3_index_orderby heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_orderby align " write [ sqlite3_index_orderby c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_orderby iColumn " write [ "iColumn" sqlite3_index_orderby offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_orderby desc " write [ "desc" sqlite3_index_orderby offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint_usage size " write [ sqlite3_index_constraint_usage heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint_usage align " write [ sqlite3_index_constraint_usage c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint_usage argvIndex " write [ "argvIndex" sqlite3_index_constraint_usage offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_index_constraint_usage omit " write [ "omit" sqlite3_index_constraint_usage offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab size " write [ sqlite3_vtab heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab align " write [ sqlite3_vtab c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab pModule " write [ "pModule" sqlite3_vtab offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab nRef " write [ "nRef" sqlite3_vtab offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab zErrMsg " write [ "zErrMsg" sqlite3_vtab offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab_cursor size " write [ sqlite3_vtab_cursor heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab_cursor align " write [ sqlite3_vtab_cursor c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_vtab_cursor pVtab " write [ "pVtab" sqlite3_vtab_cursor offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods size " write [ sqlite3_mutex_methods heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods align " write [ sqlite3_mutex_methods c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexInit " write [ "xMutexInit" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexEnd " write [ "xMutexEnd" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexAlloc " write [ "xMutexAlloc" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexFree " write [ "xMutexFree" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexEnter " write [ "xMutexEnter" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexTry " write [ "xMutexTry" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexLeave " write [ "xMutexLeave" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexHeld " write [ "xMutexHeld" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_mutex_methods xMutexNotheld " write [ "xMutexNotheld" sqlite3_mutex_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_page size " write [ sqlite3_pcache_page heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_page align " write [ sqlite3_pcache_page c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_page pBuf " write [ "pBuf" sqlite3_pcache_page offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_page pExtra " write [ "pExtra" sqlite3_pcache_page offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 size " write [ sqlite3_pcache_methods2 heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 align " write [ sqlite3_pcache_methods2 c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 iVersion " write [ "iVersion" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 pArg " write [ "pArg" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xInit " write [ "xInit" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xShutdown " write [ "xShutdown" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xCreate " write [ "xCreate" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xCachesize " write [ "xCachesize" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xPagecount " write [ "xPagecount" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xFetch " write [ "xFetch" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xUnpin " write [ "xUnpin" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xRekey " write [ "xRekey" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xTruncate " write [ "xTruncate" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xDestroy " write [ "xDestroy" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods2 xShrink " write [ "xShrink" sqlite3_pcache_methods2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods size " write [ sqlite3_pcache_methods heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods align " write [ sqlite3_pcache_methods c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods pArg " write [ "pArg" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xInit " write [ "xInit" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xShutdown " write [ "xShutdown" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xCreate " write [ "xCreate" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xCachesize " write [ "xCachesize" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xPagecount " write [ "xPagecount" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xFetch " write [ "xFetch" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xUnpin " write [ "xUnpin" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xRekey " write [ "xRekey" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xTruncate " write [ "xTruncate" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_pcache_methods xDestroy " write [ "xDestroy" sqlite3_pcache_methods offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_snapshot size " write [ sqlite3_snapshot heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_snapshot align " write [ sqlite3_snapshot c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_snapshot hidden " write [ "hidden" sqlite3_snapshot offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_geometry size " write [ sqlite3_rtree_geometry heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_geometry align " write [ sqlite3_rtree_geometry c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_geometry pContext " write [ "pContext" sqlite3_rtree_geometry offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_geometry nParam " write [ "nParam" sqlite3_rtree_geometry offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_geometry aParam " write [ "aParam" sqlite3_rtree_geometry offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_geometry pUser " write [ "pUser" sqlite3_rtree_geometry offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_geometry xDelUser " write [ "xDelUser" sqlite3_rtree_geometry offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info size " write [ sqlite3_rtree_query_info heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info align " write [ sqlite3_rtree_query_info c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info pContext " write [ "pContext" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info nParam " write [ "nParam" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info aParam " write [ "aParam" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info pUser " write [ "pUser" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info xDelUser " write [ "xDelUser" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info aCoord " write [ "aCoord" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info anQueue " write [ "anQueue" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info nCoord " write [ "nCoord" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info iLevel " write [ "iLevel" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info mxLevel " write [ "mxLevel" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info iRowid " write [ "iRowid" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info rParentScore " write [ "rParentScore" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info eParentWithin " write [ "eParentWithin" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info eWithin " write [ "eWithin" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info rScore " write [ "rScore" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT sqlite3_rtree_query_info apSqlParam " write [ "apSqlParam" sqlite3_rtree_query_info offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5PhraseIter size " write [ Fts5PhraseIter heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5PhraseIter align " write [ Fts5PhraseIter c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5PhraseIter a " write [ "a" Fts5PhraseIter offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5PhraseIter b " write [ "b" Fts5PhraseIter offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi size " write [ Fts5ExtensionApi heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi align " write [ Fts5ExtensionApi c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi iVersion " write [ "iVersion" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xUserData " write [ "xUserData" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xColumnCount " write [ "xColumnCount" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xRowCount " write [ "xRowCount" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xColumnTotalSize " write [ "xColumnTotalSize" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xTokenize " write [ "xTokenize" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xPhraseCount " write [ "xPhraseCount" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xPhraseSize " write [ "xPhraseSize" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xInstCount " write [ "xInstCount" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xInst " write [ "xInst" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xRowid " write [ "xRowid" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xColumnText " write [ "xColumnText" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xColumnSize " write [ "xColumnSize" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xQueryPhrase " write [ "xQueryPhrase" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xSetAuxdata " write [ "xSetAuxdata" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xGetAuxdata " write [ "xGetAuxdata" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xPhraseFirst " write [ "xPhraseFirst" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xPhraseNext " write [ "xPhraseNext" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xPhraseFirstColumn " write [ "xPhraseFirstColumn" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xPhraseNextColumn " write [ "xPhraseNextColumn" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xQueryToken " write [ "xQueryToken" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xInstToken " write [ "xInstToken" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xColumnLocale " write [ "xColumnLocale" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT Fts5ExtensionApi xTokenize_v2 " write [ "xTokenize_v2" Fts5ExtensionApi offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer_v2 size " write [ fts5_tokenizer_v2 heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer_v2 align " write [ fts5_tokenizer_v2 c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer_v2 iVersion " write [ "iVersion" fts5_tokenizer_v2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer_v2 xCreate " write [ "xCreate" fts5_tokenizer_v2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer_v2 xDelete " write [ "xDelete" fts5_tokenizer_v2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer_v2 xTokenize " write [ "xTokenize" fts5_tokenizer_v2 offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer size " write [ fts5_tokenizer heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer align " write [ fts5_tokenizer c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer xCreate " write [ "xCreate" fts5_tokenizer offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer xDelete " write [ "xDelete" fts5_tokenizer offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_tokenizer xTokenize " write [ "xTokenize" fts5_tokenizer offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api size " write [ fts5_api heap-size . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api align " write [ fts5_api c-type-align . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api iVersion " write [ "iVersion" fts5_api offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api xCreateTokenizer " write [ "xCreateTokenizer" fts5_api offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api xFindTokenizer " write [ "xFindTokenizer" fts5_api offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api xCreateFunction " write [ "xCreateFunction" fts5_api offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api xCreateTokenizer_v2 " write [ "xCreateTokenizer_v2" fts5_api offset-of . ] [ drop "ERROR" print ] recover
"LAYOUT fts5_api xFindTokenizer_v2 " write [ "xFindTokenizer_v2" fts5_api offset-of . ] [ drop "ERROR" print ] recover
