/* Generated from pinned official SQLite 3.53.4 header by header-audit.py. */
#include <stddef.h>
#include <stdio.h>
#define SQLITE_ENABLE_SESSION
#define SQLITE_ENABLE_PREUPDATE_HOOK
#include "../library-release-comparison-20260908/sqlite/sqlite3-3.53.4.h"
int main(void) {
  printf("LAYOUT sqlite3_file size %zu\n", sizeof(struct sqlite3_file));
  printf("LAYOUT sqlite3_file align %zu\n", _Alignof(struct sqlite3_file));
  printf("LAYOUT sqlite3_file pMethods %zu\n", offsetof(struct sqlite3_file, pMethods));
  printf("LAYOUT sqlite3_io_methods size %zu\n", sizeof(struct sqlite3_io_methods));
  printf("LAYOUT sqlite3_io_methods align %zu\n", _Alignof(struct sqlite3_io_methods));
  printf("LAYOUT sqlite3_io_methods iVersion %zu\n", offsetof(struct sqlite3_io_methods, iVersion));
  printf("LAYOUT sqlite3_io_methods xClose %zu\n", offsetof(struct sqlite3_io_methods, xClose));
  printf("LAYOUT sqlite3_io_methods xRead %zu\n", offsetof(struct sqlite3_io_methods, xRead));
  printf("LAYOUT sqlite3_io_methods xWrite %zu\n", offsetof(struct sqlite3_io_methods, xWrite));
  printf("LAYOUT sqlite3_io_methods xTruncate %zu\n", offsetof(struct sqlite3_io_methods, xTruncate));
  printf("LAYOUT sqlite3_io_methods xSync %zu\n", offsetof(struct sqlite3_io_methods, xSync));
  printf("LAYOUT sqlite3_io_methods xFileSize %zu\n", offsetof(struct sqlite3_io_methods, xFileSize));
  printf("LAYOUT sqlite3_io_methods xLock %zu\n", offsetof(struct sqlite3_io_methods, xLock));
  printf("LAYOUT sqlite3_io_methods xUnlock %zu\n", offsetof(struct sqlite3_io_methods, xUnlock));
  printf("LAYOUT sqlite3_io_methods xCheckReservedLock %zu\n", offsetof(struct sqlite3_io_methods, xCheckReservedLock));
  printf("LAYOUT sqlite3_io_methods xFileControl %zu\n", offsetof(struct sqlite3_io_methods, xFileControl));
  printf("LAYOUT sqlite3_io_methods xSectorSize %zu\n", offsetof(struct sqlite3_io_methods, xSectorSize));
  printf("LAYOUT sqlite3_io_methods xDeviceCharacteristics %zu\n", offsetof(struct sqlite3_io_methods, xDeviceCharacteristics));
  printf("LAYOUT sqlite3_io_methods xShmMap %zu\n", offsetof(struct sqlite3_io_methods, xShmMap));
  printf("LAYOUT sqlite3_io_methods xShmLock %zu\n", offsetof(struct sqlite3_io_methods, xShmLock));
  printf("LAYOUT sqlite3_io_methods xShmBarrier %zu\n", offsetof(struct sqlite3_io_methods, xShmBarrier));
  printf("LAYOUT sqlite3_io_methods xShmUnmap %zu\n", offsetof(struct sqlite3_io_methods, xShmUnmap));
  printf("LAYOUT sqlite3_io_methods xFetch %zu\n", offsetof(struct sqlite3_io_methods, xFetch));
  printf("LAYOUT sqlite3_io_methods xUnfetch %zu\n", offsetof(struct sqlite3_io_methods, xUnfetch));
  printf("LAYOUT sqlite3_vfs size %zu\n", sizeof(struct sqlite3_vfs));
  printf("LAYOUT sqlite3_vfs align %zu\n", _Alignof(struct sqlite3_vfs));
  printf("LAYOUT sqlite3_vfs iVersion %zu\n", offsetof(struct sqlite3_vfs, iVersion));
  printf("LAYOUT sqlite3_vfs szOsFile %zu\n", offsetof(struct sqlite3_vfs, szOsFile));
  printf("LAYOUT sqlite3_vfs mxPathname %zu\n", offsetof(struct sqlite3_vfs, mxPathname));
  printf("LAYOUT sqlite3_vfs pNext %zu\n", offsetof(struct sqlite3_vfs, pNext));
  printf("LAYOUT sqlite3_vfs zName %zu\n", offsetof(struct sqlite3_vfs, zName));
  printf("LAYOUT sqlite3_vfs pAppData %zu\n", offsetof(struct sqlite3_vfs, pAppData));
  printf("LAYOUT sqlite3_vfs xOpen %zu\n", offsetof(struct sqlite3_vfs, xOpen));
  printf("LAYOUT sqlite3_vfs xDelete %zu\n", offsetof(struct sqlite3_vfs, xDelete));
  printf("LAYOUT sqlite3_vfs xAccess %zu\n", offsetof(struct sqlite3_vfs, xAccess));
  printf("LAYOUT sqlite3_vfs xFullPathname %zu\n", offsetof(struct sqlite3_vfs, xFullPathname));
  printf("LAYOUT sqlite3_vfs xDlOpen %zu\n", offsetof(struct sqlite3_vfs, xDlOpen));
  printf("LAYOUT sqlite3_vfs xDlError %zu\n", offsetof(struct sqlite3_vfs, xDlError));
  printf("LAYOUT sqlite3_vfs xDlSym %zu\n", offsetof(struct sqlite3_vfs, xDlSym));
  printf("LAYOUT sqlite3_vfs xDlClose %zu\n", offsetof(struct sqlite3_vfs, xDlClose));
  printf("LAYOUT sqlite3_vfs xRandomness %zu\n", offsetof(struct sqlite3_vfs, xRandomness));
  printf("LAYOUT sqlite3_vfs xSleep %zu\n", offsetof(struct sqlite3_vfs, xSleep));
  printf("LAYOUT sqlite3_vfs xCurrentTime %zu\n", offsetof(struct sqlite3_vfs, xCurrentTime));
  printf("LAYOUT sqlite3_vfs xGetLastError %zu\n", offsetof(struct sqlite3_vfs, xGetLastError));
  printf("LAYOUT sqlite3_vfs xCurrentTimeInt64 %zu\n", offsetof(struct sqlite3_vfs, xCurrentTimeInt64));
  printf("LAYOUT sqlite3_vfs xSetSystemCall %zu\n", offsetof(struct sqlite3_vfs, xSetSystemCall));
  printf("LAYOUT sqlite3_vfs xGetSystemCall %zu\n", offsetof(struct sqlite3_vfs, xGetSystemCall));
  printf("LAYOUT sqlite3_vfs xNextSystemCall %zu\n", offsetof(struct sqlite3_vfs, xNextSystemCall));
  printf("LAYOUT sqlite3_mem_methods size %zu\n", sizeof(struct sqlite3_mem_methods));
  printf("LAYOUT sqlite3_mem_methods align %zu\n", _Alignof(struct sqlite3_mem_methods));
  printf("LAYOUT sqlite3_mem_methods xMalloc %zu\n", offsetof(struct sqlite3_mem_methods, xMalloc));
  printf("LAYOUT sqlite3_mem_methods xFree %zu\n", offsetof(struct sqlite3_mem_methods, xFree));
  printf("LAYOUT sqlite3_mem_methods xRealloc %zu\n", offsetof(struct sqlite3_mem_methods, xRealloc));
  printf("LAYOUT sqlite3_mem_methods xSize %zu\n", offsetof(struct sqlite3_mem_methods, xSize));
  printf("LAYOUT sqlite3_mem_methods xRoundup %zu\n", offsetof(struct sqlite3_mem_methods, xRoundup));
  printf("LAYOUT sqlite3_mem_methods xInit %zu\n", offsetof(struct sqlite3_mem_methods, xInit));
  printf("LAYOUT sqlite3_mem_methods xShutdown %zu\n", offsetof(struct sqlite3_mem_methods, xShutdown));
  printf("LAYOUT sqlite3_mem_methods pAppData %zu\n", offsetof(struct sqlite3_mem_methods, pAppData));
  printf("LAYOUT sqlite3_module size %zu\n", sizeof(struct sqlite3_module));
  printf("LAYOUT sqlite3_module align %zu\n", _Alignof(struct sqlite3_module));
  printf("LAYOUT sqlite3_module iVersion %zu\n", offsetof(struct sqlite3_module, iVersion));
  printf("LAYOUT sqlite3_module xCreate %zu\n", offsetof(struct sqlite3_module, xCreate));
  printf("LAYOUT sqlite3_module xConnect %zu\n", offsetof(struct sqlite3_module, xConnect));
  printf("LAYOUT sqlite3_module xBestIndex %zu\n", offsetof(struct sqlite3_module, xBestIndex));
  printf("LAYOUT sqlite3_module xDisconnect %zu\n", offsetof(struct sqlite3_module, xDisconnect));
  printf("LAYOUT sqlite3_module xDestroy %zu\n", offsetof(struct sqlite3_module, xDestroy));
  printf("LAYOUT sqlite3_module xOpen %zu\n", offsetof(struct sqlite3_module, xOpen));
  printf("LAYOUT sqlite3_module xClose %zu\n", offsetof(struct sqlite3_module, xClose));
  printf("LAYOUT sqlite3_module xFilter %zu\n", offsetof(struct sqlite3_module, xFilter));
  printf("LAYOUT sqlite3_module xNext %zu\n", offsetof(struct sqlite3_module, xNext));
  printf("LAYOUT sqlite3_module xEof %zu\n", offsetof(struct sqlite3_module, xEof));
  printf("LAYOUT sqlite3_module xColumn %zu\n", offsetof(struct sqlite3_module, xColumn));
  printf("LAYOUT sqlite3_module xRowid %zu\n", offsetof(struct sqlite3_module, xRowid));
  printf("LAYOUT sqlite3_module xUpdate %zu\n", offsetof(struct sqlite3_module, xUpdate));
  printf("LAYOUT sqlite3_module xBegin %zu\n", offsetof(struct sqlite3_module, xBegin));
  printf("LAYOUT sqlite3_module xSync %zu\n", offsetof(struct sqlite3_module, xSync));
  printf("LAYOUT sqlite3_module xCommit %zu\n", offsetof(struct sqlite3_module, xCommit));
  printf("LAYOUT sqlite3_module xRollback %zu\n", offsetof(struct sqlite3_module, xRollback));
  printf("LAYOUT sqlite3_module xFindFunction %zu\n", offsetof(struct sqlite3_module, xFindFunction));
  printf("LAYOUT sqlite3_module xRename %zu\n", offsetof(struct sqlite3_module, xRename));
  printf("LAYOUT sqlite3_module xSavepoint %zu\n", offsetof(struct sqlite3_module, xSavepoint));
  printf("LAYOUT sqlite3_module xRelease %zu\n", offsetof(struct sqlite3_module, xRelease));
  printf("LAYOUT sqlite3_module xRollbackTo %zu\n", offsetof(struct sqlite3_module, xRollbackTo));
  printf("LAYOUT sqlite3_module xShadowName %zu\n", offsetof(struct sqlite3_module, xShadowName));
  printf("LAYOUT sqlite3_module xIntegrity %zu\n", offsetof(struct sqlite3_module, xIntegrity));
  printf("LAYOUT sqlite3_index_info size %zu\n", sizeof(struct sqlite3_index_info));
  printf("LAYOUT sqlite3_index_info align %zu\n", _Alignof(struct sqlite3_index_info));
  printf("LAYOUT sqlite3_index_info nConstraint %zu\n", offsetof(struct sqlite3_index_info, nConstraint));
  printf("LAYOUT sqlite3_index_info aConstraint %zu\n", offsetof(struct sqlite3_index_info, aConstraint));
  printf("LAYOUT sqlite3_index_info nOrderBy %zu\n", offsetof(struct sqlite3_index_info, nOrderBy));
  printf("LAYOUT sqlite3_index_info aOrderBy %zu\n", offsetof(struct sqlite3_index_info, aOrderBy));
  printf("LAYOUT sqlite3_index_info aConstraintUsage %zu\n", offsetof(struct sqlite3_index_info, aConstraintUsage));
  printf("LAYOUT sqlite3_index_info idxNum %zu\n", offsetof(struct sqlite3_index_info, idxNum));
  printf("LAYOUT sqlite3_index_info idxStr %zu\n", offsetof(struct sqlite3_index_info, idxStr));
  printf("LAYOUT sqlite3_index_info needToFreeIdxStr %zu\n", offsetof(struct sqlite3_index_info, needToFreeIdxStr));
  printf("LAYOUT sqlite3_index_info orderByConsumed %zu\n", offsetof(struct sqlite3_index_info, orderByConsumed));
  printf("LAYOUT sqlite3_index_info estimatedCost %zu\n", offsetof(struct sqlite3_index_info, estimatedCost));
  printf("LAYOUT sqlite3_index_info estimatedRows %zu\n", offsetof(struct sqlite3_index_info, estimatedRows));
  printf("LAYOUT sqlite3_index_info idxFlags %zu\n", offsetof(struct sqlite3_index_info, idxFlags));
  printf("LAYOUT sqlite3_index_info colUsed %zu\n", offsetof(struct sqlite3_index_info, colUsed));
  printf("LAYOUT sqlite3_index_constraint size %zu\n", sizeof(struct sqlite3_index_constraint));
  printf("LAYOUT sqlite3_index_constraint align %zu\n", _Alignof(struct sqlite3_index_constraint));
  printf("LAYOUT sqlite3_index_constraint iColumn %zu\n", offsetof(struct sqlite3_index_constraint, iColumn));
  printf("LAYOUT sqlite3_index_constraint op %zu\n", offsetof(struct sqlite3_index_constraint, op));
  printf("LAYOUT sqlite3_index_constraint usable %zu\n", offsetof(struct sqlite3_index_constraint, usable));
  printf("LAYOUT sqlite3_index_constraint iTermOffset %zu\n", offsetof(struct sqlite3_index_constraint, iTermOffset));
  printf("LAYOUT sqlite3_index_orderby size %zu\n", sizeof(struct sqlite3_index_orderby));
  printf("LAYOUT sqlite3_index_orderby align %zu\n", _Alignof(struct sqlite3_index_orderby));
  printf("LAYOUT sqlite3_index_orderby iColumn %zu\n", offsetof(struct sqlite3_index_orderby, iColumn));
  printf("LAYOUT sqlite3_index_orderby desc %zu\n", offsetof(struct sqlite3_index_orderby, desc));
  printf("LAYOUT sqlite3_index_constraint_usage size %zu\n", sizeof(struct sqlite3_index_constraint_usage));
  printf("LAYOUT sqlite3_index_constraint_usage align %zu\n", _Alignof(struct sqlite3_index_constraint_usage));
  printf("LAYOUT sqlite3_index_constraint_usage argvIndex %zu\n", offsetof(struct sqlite3_index_constraint_usage, argvIndex));
  printf("LAYOUT sqlite3_index_constraint_usage omit %zu\n", offsetof(struct sqlite3_index_constraint_usage, omit));
  printf("LAYOUT sqlite3_vtab size %zu\n", sizeof(struct sqlite3_vtab));
  printf("LAYOUT sqlite3_vtab align %zu\n", _Alignof(struct sqlite3_vtab));
  printf("LAYOUT sqlite3_vtab pModule %zu\n", offsetof(struct sqlite3_vtab, pModule));
  printf("LAYOUT sqlite3_vtab nRef %zu\n", offsetof(struct sqlite3_vtab, nRef));
  printf("LAYOUT sqlite3_vtab zErrMsg %zu\n", offsetof(struct sqlite3_vtab, zErrMsg));
  printf("LAYOUT sqlite3_vtab_cursor size %zu\n", sizeof(struct sqlite3_vtab_cursor));
  printf("LAYOUT sqlite3_vtab_cursor align %zu\n", _Alignof(struct sqlite3_vtab_cursor));
  printf("LAYOUT sqlite3_vtab_cursor pVtab %zu\n", offsetof(struct sqlite3_vtab_cursor, pVtab));
  printf("LAYOUT sqlite3_mutex_methods size %zu\n", sizeof(struct sqlite3_mutex_methods));
  printf("LAYOUT sqlite3_mutex_methods align %zu\n", _Alignof(struct sqlite3_mutex_methods));
  printf("LAYOUT sqlite3_mutex_methods xMutexInit %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexInit));
  printf("LAYOUT sqlite3_mutex_methods xMutexEnd %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexEnd));
  printf("LAYOUT sqlite3_mutex_methods xMutexAlloc %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexAlloc));
  printf("LAYOUT sqlite3_mutex_methods xMutexFree %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexFree));
  printf("LAYOUT sqlite3_mutex_methods xMutexEnter %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexEnter));
  printf("LAYOUT sqlite3_mutex_methods xMutexTry %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexTry));
  printf("LAYOUT sqlite3_mutex_methods xMutexLeave %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexLeave));
  printf("LAYOUT sqlite3_mutex_methods xMutexHeld %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexHeld));
  printf("LAYOUT sqlite3_mutex_methods xMutexNotheld %zu\n", offsetof(struct sqlite3_mutex_methods, xMutexNotheld));
  printf("LAYOUT sqlite3_pcache_page size %zu\n", sizeof(struct sqlite3_pcache_page));
  printf("LAYOUT sqlite3_pcache_page align %zu\n", _Alignof(struct sqlite3_pcache_page));
  printf("LAYOUT sqlite3_pcache_page pBuf %zu\n", offsetof(struct sqlite3_pcache_page, pBuf));
  printf("LAYOUT sqlite3_pcache_page pExtra %zu\n", offsetof(struct sqlite3_pcache_page, pExtra));
  printf("LAYOUT sqlite3_pcache_methods2 size %zu\n", sizeof(struct sqlite3_pcache_methods2));
  printf("LAYOUT sqlite3_pcache_methods2 align %zu\n", _Alignof(struct sqlite3_pcache_methods2));
  printf("LAYOUT sqlite3_pcache_methods2 iVersion %zu\n", offsetof(struct sqlite3_pcache_methods2, iVersion));
  printf("LAYOUT sqlite3_pcache_methods2 pArg %zu\n", offsetof(struct sqlite3_pcache_methods2, pArg));
  printf("LAYOUT sqlite3_pcache_methods2 xInit %zu\n", offsetof(struct sqlite3_pcache_methods2, xInit));
  printf("LAYOUT sqlite3_pcache_methods2 xShutdown %zu\n", offsetof(struct sqlite3_pcache_methods2, xShutdown));
  printf("LAYOUT sqlite3_pcache_methods2 xCreate %zu\n", offsetof(struct sqlite3_pcache_methods2, xCreate));
  printf("LAYOUT sqlite3_pcache_methods2 xCachesize %zu\n", offsetof(struct sqlite3_pcache_methods2, xCachesize));
  printf("LAYOUT sqlite3_pcache_methods2 xPagecount %zu\n", offsetof(struct sqlite3_pcache_methods2, xPagecount));
  printf("LAYOUT sqlite3_pcache_methods2 xFetch %zu\n", offsetof(struct sqlite3_pcache_methods2, xFetch));
  printf("LAYOUT sqlite3_pcache_methods2 xUnpin %zu\n", offsetof(struct sqlite3_pcache_methods2, xUnpin));
  printf("LAYOUT sqlite3_pcache_methods2 xRekey %zu\n", offsetof(struct sqlite3_pcache_methods2, xRekey));
  printf("LAYOUT sqlite3_pcache_methods2 xTruncate %zu\n", offsetof(struct sqlite3_pcache_methods2, xTruncate));
  printf("LAYOUT sqlite3_pcache_methods2 xDestroy %zu\n", offsetof(struct sqlite3_pcache_methods2, xDestroy));
  printf("LAYOUT sqlite3_pcache_methods2 xShrink %zu\n", offsetof(struct sqlite3_pcache_methods2, xShrink));
  printf("LAYOUT sqlite3_pcache_methods size %zu\n", sizeof(struct sqlite3_pcache_methods));
  printf("LAYOUT sqlite3_pcache_methods align %zu\n", _Alignof(struct sqlite3_pcache_methods));
  printf("LAYOUT sqlite3_pcache_methods pArg %zu\n", offsetof(struct sqlite3_pcache_methods, pArg));
  printf("LAYOUT sqlite3_pcache_methods xInit %zu\n", offsetof(struct sqlite3_pcache_methods, xInit));
  printf("LAYOUT sqlite3_pcache_methods xShutdown %zu\n", offsetof(struct sqlite3_pcache_methods, xShutdown));
  printf("LAYOUT sqlite3_pcache_methods xCreate %zu\n", offsetof(struct sqlite3_pcache_methods, xCreate));
  printf("LAYOUT sqlite3_pcache_methods xCachesize %zu\n", offsetof(struct sqlite3_pcache_methods, xCachesize));
  printf("LAYOUT sqlite3_pcache_methods xPagecount %zu\n", offsetof(struct sqlite3_pcache_methods, xPagecount));
  printf("LAYOUT sqlite3_pcache_methods xFetch %zu\n", offsetof(struct sqlite3_pcache_methods, xFetch));
  printf("LAYOUT sqlite3_pcache_methods xUnpin %zu\n", offsetof(struct sqlite3_pcache_methods, xUnpin));
  printf("LAYOUT sqlite3_pcache_methods xRekey %zu\n", offsetof(struct sqlite3_pcache_methods, xRekey));
  printf("LAYOUT sqlite3_pcache_methods xTruncate %zu\n", offsetof(struct sqlite3_pcache_methods, xTruncate));
  printf("LAYOUT sqlite3_pcache_methods xDestroy %zu\n", offsetof(struct sqlite3_pcache_methods, xDestroy));
  printf("LAYOUT sqlite3_snapshot size %zu\n", sizeof(struct sqlite3_snapshot));
  printf("LAYOUT sqlite3_snapshot align %zu\n", _Alignof(struct sqlite3_snapshot));
  printf("LAYOUT sqlite3_snapshot hidden %zu\n", offsetof(struct sqlite3_snapshot, hidden));
  printf("LAYOUT sqlite3_rtree_geometry size %zu\n", sizeof(struct sqlite3_rtree_geometry));
  printf("LAYOUT sqlite3_rtree_geometry align %zu\n", _Alignof(struct sqlite3_rtree_geometry));
  printf("LAYOUT sqlite3_rtree_geometry pContext %zu\n", offsetof(struct sqlite3_rtree_geometry, pContext));
  printf("LAYOUT sqlite3_rtree_geometry nParam %zu\n", offsetof(struct sqlite3_rtree_geometry, nParam));
  printf("LAYOUT sqlite3_rtree_geometry aParam %zu\n", offsetof(struct sqlite3_rtree_geometry, aParam));
  printf("LAYOUT sqlite3_rtree_geometry pUser %zu\n", offsetof(struct sqlite3_rtree_geometry, pUser));
  printf("LAYOUT sqlite3_rtree_geometry xDelUser %zu\n", offsetof(struct sqlite3_rtree_geometry, xDelUser));
  printf("LAYOUT sqlite3_rtree_query_info size %zu\n", sizeof(struct sqlite3_rtree_query_info));
  printf("LAYOUT sqlite3_rtree_query_info align %zu\n", _Alignof(struct sqlite3_rtree_query_info));
  printf("LAYOUT sqlite3_rtree_query_info pContext %zu\n", offsetof(struct sqlite3_rtree_query_info, pContext));
  printf("LAYOUT sqlite3_rtree_query_info nParam %zu\n", offsetof(struct sqlite3_rtree_query_info, nParam));
  printf("LAYOUT sqlite3_rtree_query_info aParam %zu\n", offsetof(struct sqlite3_rtree_query_info, aParam));
  printf("LAYOUT sqlite3_rtree_query_info pUser %zu\n", offsetof(struct sqlite3_rtree_query_info, pUser));
  printf("LAYOUT sqlite3_rtree_query_info xDelUser %zu\n", offsetof(struct sqlite3_rtree_query_info, xDelUser));
  printf("LAYOUT sqlite3_rtree_query_info aCoord %zu\n", offsetof(struct sqlite3_rtree_query_info, aCoord));
  printf("LAYOUT sqlite3_rtree_query_info anQueue %zu\n", offsetof(struct sqlite3_rtree_query_info, anQueue));
  printf("LAYOUT sqlite3_rtree_query_info nCoord %zu\n", offsetof(struct sqlite3_rtree_query_info, nCoord));
  printf("LAYOUT sqlite3_rtree_query_info iLevel %zu\n", offsetof(struct sqlite3_rtree_query_info, iLevel));
  printf("LAYOUT sqlite3_rtree_query_info mxLevel %zu\n", offsetof(struct sqlite3_rtree_query_info, mxLevel));
  printf("LAYOUT sqlite3_rtree_query_info iRowid %zu\n", offsetof(struct sqlite3_rtree_query_info, iRowid));
  printf("LAYOUT sqlite3_rtree_query_info rParentScore %zu\n", offsetof(struct sqlite3_rtree_query_info, rParentScore));
  printf("LAYOUT sqlite3_rtree_query_info eParentWithin %zu\n", offsetof(struct sqlite3_rtree_query_info, eParentWithin));
  printf("LAYOUT sqlite3_rtree_query_info eWithin %zu\n", offsetof(struct sqlite3_rtree_query_info, eWithin));
  printf("LAYOUT sqlite3_rtree_query_info rScore %zu\n", offsetof(struct sqlite3_rtree_query_info, rScore));
  printf("LAYOUT sqlite3_rtree_query_info apSqlParam %zu\n", offsetof(struct sqlite3_rtree_query_info, apSqlParam));
  printf("LAYOUT Fts5PhraseIter size %zu\n", sizeof(struct Fts5PhraseIter));
  printf("LAYOUT Fts5PhraseIter align %zu\n", _Alignof(struct Fts5PhraseIter));
  printf("LAYOUT Fts5PhraseIter a %zu\n", offsetof(struct Fts5PhraseIter, a));
  printf("LAYOUT Fts5PhraseIter b %zu\n", offsetof(struct Fts5PhraseIter, b));
  printf("LAYOUT Fts5ExtensionApi size %zu\n", sizeof(struct Fts5ExtensionApi));
  printf("LAYOUT Fts5ExtensionApi align %zu\n", _Alignof(struct Fts5ExtensionApi));
  printf("LAYOUT Fts5ExtensionApi iVersion %zu\n", offsetof(struct Fts5ExtensionApi, iVersion));
  printf("LAYOUT Fts5ExtensionApi xUserData %zu\n", offsetof(struct Fts5ExtensionApi, xUserData));
  printf("LAYOUT Fts5ExtensionApi xColumnCount %zu\n", offsetof(struct Fts5ExtensionApi, xColumnCount));
  printf("LAYOUT Fts5ExtensionApi xRowCount %zu\n", offsetof(struct Fts5ExtensionApi, xRowCount));
  printf("LAYOUT Fts5ExtensionApi xColumnTotalSize %zu\n", offsetof(struct Fts5ExtensionApi, xColumnTotalSize));
  printf("LAYOUT Fts5ExtensionApi xTokenize %zu\n", offsetof(struct Fts5ExtensionApi, xTokenize));
  printf("LAYOUT Fts5ExtensionApi xPhraseCount %zu\n", offsetof(struct Fts5ExtensionApi, xPhraseCount));
  printf("LAYOUT Fts5ExtensionApi xPhraseSize %zu\n", offsetof(struct Fts5ExtensionApi, xPhraseSize));
  printf("LAYOUT Fts5ExtensionApi xInstCount %zu\n", offsetof(struct Fts5ExtensionApi, xInstCount));
  printf("LAYOUT Fts5ExtensionApi xInst %zu\n", offsetof(struct Fts5ExtensionApi, xInst));
  printf("LAYOUT Fts5ExtensionApi xRowid %zu\n", offsetof(struct Fts5ExtensionApi, xRowid));
  printf("LAYOUT Fts5ExtensionApi xColumnText %zu\n", offsetof(struct Fts5ExtensionApi, xColumnText));
  printf("LAYOUT Fts5ExtensionApi xColumnSize %zu\n", offsetof(struct Fts5ExtensionApi, xColumnSize));
  printf("LAYOUT Fts5ExtensionApi xQueryPhrase %zu\n", offsetof(struct Fts5ExtensionApi, xQueryPhrase));
  printf("LAYOUT Fts5ExtensionApi xSetAuxdata %zu\n", offsetof(struct Fts5ExtensionApi, xSetAuxdata));
  printf("LAYOUT Fts5ExtensionApi xGetAuxdata %zu\n", offsetof(struct Fts5ExtensionApi, xGetAuxdata));
  printf("LAYOUT Fts5ExtensionApi xPhraseFirst %zu\n", offsetof(struct Fts5ExtensionApi, xPhraseFirst));
  printf("LAYOUT Fts5ExtensionApi xPhraseNext %zu\n", offsetof(struct Fts5ExtensionApi, xPhraseNext));
  printf("LAYOUT Fts5ExtensionApi xPhraseFirstColumn %zu\n", offsetof(struct Fts5ExtensionApi, xPhraseFirstColumn));
  printf("LAYOUT Fts5ExtensionApi xPhraseNextColumn %zu\n", offsetof(struct Fts5ExtensionApi, xPhraseNextColumn));
  printf("LAYOUT Fts5ExtensionApi xQueryToken %zu\n", offsetof(struct Fts5ExtensionApi, xQueryToken));
  printf("LAYOUT Fts5ExtensionApi xInstToken %zu\n", offsetof(struct Fts5ExtensionApi, xInstToken));
  printf("LAYOUT Fts5ExtensionApi xColumnLocale %zu\n", offsetof(struct Fts5ExtensionApi, xColumnLocale));
  printf("LAYOUT Fts5ExtensionApi xTokenize_v2 %zu\n", offsetof(struct Fts5ExtensionApi, xTokenize_v2));
  printf("LAYOUT fts5_tokenizer_v2 size %zu\n", sizeof(struct fts5_tokenizer_v2));
  printf("LAYOUT fts5_tokenizer_v2 align %zu\n", _Alignof(struct fts5_tokenizer_v2));
  printf("LAYOUT fts5_tokenizer_v2 iVersion %zu\n", offsetof(struct fts5_tokenizer_v2, iVersion));
  printf("LAYOUT fts5_tokenizer_v2 xCreate %zu\n", offsetof(struct fts5_tokenizer_v2, xCreate));
  printf("LAYOUT fts5_tokenizer_v2 xDelete %zu\n", offsetof(struct fts5_tokenizer_v2, xDelete));
  printf("LAYOUT fts5_tokenizer_v2 xTokenize %zu\n", offsetof(struct fts5_tokenizer_v2, xTokenize));
  printf("LAYOUT fts5_tokenizer size %zu\n", sizeof(struct fts5_tokenizer));
  printf("LAYOUT fts5_tokenizer align %zu\n", _Alignof(struct fts5_tokenizer));
  printf("LAYOUT fts5_tokenizer xCreate %zu\n", offsetof(struct fts5_tokenizer, xCreate));
  printf("LAYOUT fts5_tokenizer xDelete %zu\n", offsetof(struct fts5_tokenizer, xDelete));
  printf("LAYOUT fts5_tokenizer xTokenize %zu\n", offsetof(struct fts5_tokenizer, xTokenize));
  printf("LAYOUT fts5_api size %zu\n", sizeof(struct fts5_api));
  printf("LAYOUT fts5_api align %zu\n", _Alignof(struct fts5_api));
  printf("LAYOUT fts5_api iVersion %zu\n", offsetof(struct fts5_api, iVersion));
  printf("LAYOUT fts5_api xCreateTokenizer %zu\n", offsetof(struct fts5_api, xCreateTokenizer));
  printf("LAYOUT fts5_api xFindTokenizer %zu\n", offsetof(struct fts5_api, xFindTokenizer));
  printf("LAYOUT fts5_api xCreateFunction %zu\n", offsetof(struct fts5_api, xCreateFunction));
  printf("LAYOUT fts5_api xCreateTokenizer_v2 %zu\n", offsetof(struct fts5_api, xCreateTokenizer_v2));
  printf("LAYOUT fts5_api xFindTokenizer_v2 %zu\n", offsetof(struct fts5_api, xFindTokenizer_v2));
  return 0;
}
