USING: alien.c-types alien.syntax ;
IN: windows.directx.dcommon

ENUM: DWRITE_MEASURING_MODE
    DWRITE_MEASURING_MODE_NATURAL
    DWRITE_MEASURING_MODE_GDI_CLASSIC
    DWRITE_MEASURING_MODE_GDI_NATURAL ;
