USING: alien.c-types alien.syntax ;
IN: windows.directx.dcommon

C-ENUM: DWRITE_MEASURING_MODE_NATURAL
        DWRITE_MEASURING_MODE_GDI_CLASSIC
        DWRITE_MEASURING_MODE_GDI_NATURAL ;
TYPEDEF: int DWRITE_MEASURING_MODE
