IN: win32-api
USING: alien kernel errors ;

: GHND HEX: 40 ; inline
: GMEM_FIXED 0 ; inline
: GMEM_MOVEABLE 2 ; inline
: GMEM_ZEROINIT HEX: 40 ; inline
: GPTR HEX: 40 ; inline

: GENERIC_READ    HEX: 80000000 ;
: GENERIC_WRITE   HEX: 40000000 ;
: GENERIC_EXECUTE HEX: 20000000 ;
: GENERIC_ALL     HEX: 10000000 ;

: CREATE_NEW        1 ;
: CREATE_ALWAYS     2 ;
: OPEN_EXISTING     3 ;
: OPEN_ALWAYS       4 ;
: TRUNCATE_EXISTING 5 ;

: FILE_SHARE_READ 1 ;
: FILE_SHARE_WRITE 2 ;
: FILE_SHARE_DELETE 4 ;

: FILE_FLAG_WRITE_THROUGH       HEX: 80000000 ;
: FILE_FLAG_OVERLAPPED          HEX: 40000000 ;
: FILE_FLAG_NO_BUFFERING        HEX: 20000000 ;
: FILE_FLAG_RANDOM_ACCESS       HEX: 10000000 ;
: FILE_FLAG_SEQUENTIAL_SCAN     HEX: 08000000 ;
: FILE_FLAG_DELETE_ON_CLOSE     HEX: 04000000 ;
: FILE_FLAG_BACKUP_SEMANTICS    HEX: 02000000 ;
: FILE_FLAG_POSIX_SEMANTICS     HEX: 01000000 ;
: FILE_FLAG_OPEN_REPARSE_POINT  HEX: 00200000 ;
: FILE_FLAG_OPEN_NO_RECALL      HEX: 00100000 ;
: FILE_FLAG_FIRST_PIPE_INSTANCE HEX: 00080000 ;

: STD_INPUT_HANDLE  -10 ;
: STD_OUTPUT_HANDLE -11 ;
: STD_ERROR_HANDLE  -12 ;

: INVALID_HANDLE_VALUE -1 <alien> ;
: INVALID_FILE_SIZE HEX: FFFFFFFF ;

: INFINITE HEX: FFFFFFFF ;

! From C:\cygwin\usr\include\w32api\winbase.h
: FILE_TYPE_UNKNOWN 0 ;
: FILE_TYPE_DISK 1 ;
: FILE_TYPE_CHAR 2 ;
: FILE_TYPE_PIPE 3 ;
: FILE_TYPE_REMOTE HEX: 8000 ;

: TIME_ZONE_ID_UNKNOWN 0 ; inline
: TIME_ZONE_ID_STANDARD 1 ; inline
: TIME_ZONE_ID_DAYLIGHT 2 ; inline
: TIME_ZONE_ID_INVALID HEX: FFFFFFFF ; inline


: CREATE_DEFAULT_ERROR_MODE HEX: 4000000 ; inline
: DETACHED_PROCESS 8 ; inline
: PF_XMMI64_INSTRUCTIONS_AVAILABLE 10 ; inline
: PF_SSE3_INSTRUCTIONS_AVAILABLE 13 ; inline

: MAX_COMPUTERNAME_LENGTH 15 ; inline
: UNLEN 256 ; inline

: PROCESS_TERMINATE ( -- number ) HEX: 1 ; inline
: PROCESS_CREATE_THREAD ( -- number ) HEX: 2 ; inline
: PROCESS_VM_OPERATION ( -- number ) HEX: 8 ; inline
: PROCESS_VM_READ ( -- number ) HEX: 10 ; inline
: PROCESS_VM_WRITE ( -- number ) HEX: 20 ; inline
: PROCESS_DUP_HANDLE ( -- number ) HEX: 40 ; inline
: PROCESS_CREATE_PROCESS ( -- number ) HEX: 80 ; inline
: PROCESS_SET_QUOTA ( -- number ) HEX: 100 ; inline
: PROCESS_SET_INFORMATION ( -- number ) HEX: 200 ; inline
: PROCESS_QUERY_INFORMATION ( -- number ) HEX: 400 ; inline

: PAGE_READWRITE ( -- number ) HEX: 4 ; inline
: MEM_COMMIT ( -- number ) HEX: 1000 ; inline
: MEM_RELEASE ( -- number ) HEX: 8000 ; inline
