PROVIDE: doc/handbook {
    "alien.facts"
    "changes.facts"
    "cli.facts"
    "collections.facts"
    "compiler.facts"
    "conventions.facts"
    "cookbook.facts"
    "dataflow.facts"
    "handbook.facts"
    "hashtables.facts"
    "help.facts"
    "inference.facts"
    "math.facts"
    "objects.facts"
    "parser.facts"
    "prettyprinter.facts"
    "sequences.facts"
    "streams.facts"
    "syntax.facts"
    "tools.facts"
    "words.facts"
} ;
