#!/bin/sh
# Help function
###############
help () {
    cat <<EOF
Usage: factor-export IMAGE FILE [ WORDS ]

Export words from a Factor image as ASCII source code.

Options:

   none so far

   If FILE is a single hypen (-), code will be written to
   standard output.

This is useful for moving Factor code in bulk between
incompatible systems, such as different architectures or
when the image format changes.  An example of this is:

    factor-export image.x86 | ssh host factor-import image.ppc

It is also useful for managing changes in a Factor codebase.
EOF
    exit 0
}

# Default values
################

# Argument parsing
##################

# Logic
#######
echo 'Sorry, this is just a stub at the moment.'
help
exit 1
