name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./build.sh update
    - name: test-core
      run: "./factor -e=\"USE: zealot.factor USE: tools.test USE: tools.test.private [ zealot-core-vocabs test-vocabs ] with-child-options\""
  
