name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bootstrap
      run: ./build.sh net-bootstrap
    - name: load
      run: "./factor -e='USING: memory namespaces parser.notes vocabs.hierarchy ; parser-quiet? off \"resource:basis\" \"\" load-from-root save'"
    - name: configure
      run: "./factor -e='USING: memory namespaces tools.test ; f long-unit-tests-enabled? set-global save'"
    - name: test
      run: "./factor -run=tools.test resource:core"
    - name: help-lint
      run: "./factor -run=help.lint resource:core resource:basis"

  build-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: arch -x86_64 ./build.sh net-bootstrap
    - name: load
      run: "./factor -e='USING: memory namespaces parser.notes vocabs.hierarchy ; parser-quiet? off \"resource:basis\" \"\" load-from-root save'"
    - name: configure
      run: "./factor -e='USING: memory namespaces tools.test ; f long-unit-tests-enabled? set-global save'"
    - name: test
      run: "./factor -run=tools.test resource:core"
    - name: help-lint
      run: "./factor -run=help.lint resource:core resource:basis"
